#!/usr/bin/env sh

for file in $(ls /sys/bus/usb/devices/*/power/autosuspend); do
	echo 0 | sudo tee "$file"
done

for file in $(ls /sys/bus/usb/devices/*/power/autosuspend_delay_ms); do
	echo 10000 | sudo tee "$file"
done

