#!/usr/bin/env sh

for file in $(ls /sys/bus/usb/devices/*/power/autosuspend); do
	echo 1 | sudo tee "$file"
done

for file in $(ls /sys/bus/usb/devices/*/power/autosuspend_delay_ms); do
	echo 100 | sudo tee "$file"
done

