#!/usr/bin/env sh

# cpu=$(rg 'cpu ' /proc/stat | awk '{printf("%.0f\n", ($2 + $4) * 100 / ($2 + $4 + $5))}')
# mem=$(free | rg Mem | awk '{printf("%.0f\n", ($2 - $7) / $2 * 100)}')
# temp=$(sort -nr /sys/class/thermal/thermal_zone*/temp | head -n1 | awk '{printf("%d°C\n", $1 / 1000)}')
# date="$(LC_TIME=C date +'%a, %d/%m/%Y (%b)')"

bat=$(power_human)
date="$(LC_TIME=C date +'%-d/%-m (%b)')"
time="$(LC_TIME=C date +'%I:%M %p')"

current="$(workspace_name)"
bar=""

for ws in $(bspwm_workspace_list); do
	if [ "$current" = "$ws" ]; then
		bar="$bar<b>[$ws]</b> "
	else
		bar="$bar$ws "
	fi
done

bar=${bar%?}

notify_status \
"$bar
<b>time</b> $time
<b>date</b> $date
<b>bat</b>  $bat
<b>mode</b> $(workspace_state)
"
