#!/usr/bin/env sh

out="$(mktemp).png"

ffmpeg -loglevel warning -i "$@" -filter_complex \
	"[0:a]aformat=channel_layouts=mono, \
	compand=gain=-6, \
	showwavespic=s=600x120:colors=#9cf42f[fg]; \
	color=s=600x120:color=#44582c, \
	drawgrid=width=iw/10:height=ih/5:color=#9cf42f@0.1[bg]; \
	[bg][fg]overlay=format=auto,drawbox=x=(iw-w)/2:y=(ih-h)/2:w=iw:h=1:color=#9cf42f" \
	-frames:v 1 "$out" && $VIEWER "$out"

