#!/usr/bin/env sh

# https://github.com/baskerville/bspwm/blob/master/examples/panel/panel

pgrep -f "$BAR_NAME" && exit 1

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$BAR_FIFO" ] && rm "$BAR_FIFO"
mkfifo "$BAR_FIFO"

# Functions
get_date() { LC_TIME=C date +'%-d/%-m (%A)'; }
get_time() { LC_TIME=C date +'%I:%M %p'; }

# Daemons
while true; do
	printf 'B%s\n' "$(power_human)"; sleep 60
done > "$BAR_FIFO" &

while true; do
	printf 'T%s\n' "$(get_time)"; sleep 60
done > "$BAR_FIFO" &

while true; do
	printf 'D%s\n' "$(get_date)"; sleep 60
done > "$BAR_FIFO" &

# cat "$HOTKEY_FIFO" | while read -r hk; do
# 	printf 'H%s\n' "${hk}"
# done > "$BAR_FIFO" &

bspc subscribe report > "$BAR_FIFO" &

# Launch bar.
bar < "$BAR_FIFO" | lemonbar -f "$BAR_FONT" -d -b -n "$BAR_NAME" | sh &

# Force refresh on startup
bar_refresh

wait
