#!/usr/bin/env sh




if ping 8.8.8.8 -c 2 > /dev/null 2>&1 && networking_ip_private > /dev/null; then
	echo "up/$(networking_ip_private)"
	exit 0

elif ping 8.8.8.8 -c 2 > /dev/null 2>&1; then
	echo "up"
	exit 0
fi

echo "down"
exit 1

