#!/usr/bin/env sh


choices="pick\nnew\nreset"
chosen=$(echo "$choices" | dmenu -p "wallpaper")


case "$chosen" in

	new)           wallpaper_random;;
	pick)          wallpaper_choose;;
	reset)         wallpaper_reset;;

esac
