#!/usr/bin/env sh


choices="session\nutils\nmonitors\nwallpapers"
chosen=$(echo "$choices" | dmenu -p "tools")


case "$chosen" in

	session)    prompt_power;;
	utils)      prompt_utils;;
	monitors)   prompt_monitor;;
	wallpapers) prompt_wallpaper;;

esac
