#!/usr/bin/env sh

i=0
perc=0

test -f /sys/class/power_supply/BAT*/capacity || exit 1

for bat in `cat /sys/class/power_supply/BAT*/capacity`; do
	i=$(( i + 1 ))
	perc=$(( perc + bat ))
done

echo $(( perc / i ))
