#!/usr/bin/env sh


test -f "/sys/class/power_supply/AC/online" || exit 1

is_connect="$(cat /sys/class/power_supply/AC/online)"

case "$is_connect" in
	0) echo "disconnected" && exit 1;;
	1) echo "connected" && exit 0;;
esac


echo "unknown"
exit 0
