#!/usr/bin/env sh

set -- /sys/class/power_supply/BAT*
[ ! -e "$1" ] && return
read STAT < "$1"/status

i=0
perc=0

while [ $# -gt 0 ]; do
	read cap < "$1"/capacity
	perc=$((perc+cap))
	i=$((i+1))
	shift
done

perc=$((perc/i))
echo "$perc"
