#!/usr/bin/env sh

fname=$(zenity --file-selection --save --confirm-overwrite --filename "$1")

if [ -z "$fname" ]; then
	exit 1
fi

xclip -selection clipboard -o > "$fname"  # save to file from clipboard
