#!/usr/bin/env sh

notice() {
	echo "$@"
}

# Setup monitors and workspaces.
autorandr -c
bspwm_monitor_dist

# Configure BSPWM.
bspwm_config
bspwm_rules

# Launch programs.
run_once bar_run
run_once launch_sxhkd
run_once launch_picom

# run_once pulseaudio --start
# pidof -s runit &&
# 	! pidof -s pulseaudio >/dev/null 2>&1 &&
# 	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

# Pipewire
run_once pipewire
run_once pipewire-pulse

run_once dunst

# Set mouse pointer and keyboard layout.
xsetroot -cursor_name left_ptr
keyboard_set

wallpaper_random

# Hide cursor after a period of inactivity.
run_once unclutter -idle 2 -jitter 1 -reset

# Disable touchpad while typing.
run_once syndaemon -K -i 0.125 -R

# Don't destroy my ears.
volume_set 20

# Relaunch daemons for tracking battery and network.
launch_daemons() {
	notice "launching daemons"

	pkill -f daemon_networking
	pkill -f daemon_battery_notifier

	daemon_battery_notifier &
	daemon_networking &
}


x240_setup_kb_mouse() {
	notice "setting up x240 keyboard & mouse"

	xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Speed" -.3
	# xinput set-prop "Synaptics TM3075-008" "libinput Tapping Enabled" 1
	synclient TapButton1=1

	xmodmap -e "keycode 118 = End"
}


x230_setup_kb_mouse() {
	notice "setting up x230 keyboard & mouse"
	xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Speed" 1

	synclient PalmDetect=1   # ignore palm
	synclient PalmMinZ=100
	synclient PalmMinWidth=8
	synclient TapButton1=1   # tap to click
	synclient HorizTwoFingerScroll=1
	synclient CoastingSpeed=0
	synclient FingerLow=35
	synclient FingerHigh=40

	# Remap back/forward to pgup/pgdown
	xmodmap -e "keycode 167 = Next"
	xmodmap -e "keycode 166 = Prior"

	# # Remap Home/PgUp to Home/End
	# xmodmap -e "keycode 110 = Home"
	# xmodmap -e "keycode 112 = End"

	# xmodmap -e "keycode 115 = Prior"
	# xmodmap -e "keycode 117 = Next"
}


# Setup model specific settings.
model="$(cat /sys/devices/virtual/dmi/id/product_version /sys/devices/virtual/dmi/id/product_name)"

if echo "$model" | rg "ThinkPad X240"; then
	notice "detected x240"

	launch_daemons
	x240_setup_kb_mouse

elif echo "$model" | rg "ThinkPad X230"; then
	notice "detected x230"

	launch_daemons
	x230_setup_kb_mouse

elif echo "$model" | rg "MS-7693"; then
	notice "detected amd fx desktop"
fi


# use gpu scaler
displays="$(xrandr -q | rg '[^dis]connected' | cut -d' ' -f1)"
for output in $displays; do
	xrandr --output "$output" --set "scaling mode" "Full"
done

for output in $displays; do
	xrandr --output "$output" --set "TearFree" "on"
done

