#!/usr/bin/env sh

bspc wm --adopt-orphans
bspc wm --record-history on


# --- GAPS & BORDERS ---
bspc config border_width 1
bspc config split_ratio  0.5
bspc config window_gap   -1

bspc config top_padding    1
bspc config bottom_padding 13
bspc config left_padding   1
bspc config right_padding  1

bspc config top_monocle_padding    -1
bspc config bottom_monocle_padding -1
bspc config left_monocle_padding   -1
bspc config right_monocle_padding  -1


# --- NODE ---
bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config single_monocle     true

bspc config directional_focus_tightness high
bspc config removal_adjustment          true
bspc config automatic_scheme            longest_side
bspc config initial_polarity            second_child

bspc config ignore_ewmh_focus true


# --- MOUSE ---
bspc config focus_follows_pointer   true
bspc config click_to_focus          any
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor true
bspc config swallow_first_click     true

bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner


# --- COLOURS ---
bspc config normal_border_color   "#0D0D0D"
bspc config active_border_color   "#888888"
bspc config focused_border_color  "#FFFFFF"
bspc config presel_feedback_color "#AADD22"


# --- MONITORS ---
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors false
