#!/usr/bin/env sh


choices="mount\nunmount\neject"
chosen=$(echo "$choices" | dmenu -p "usb")


case "$chosen" in

	mount)   prompt_usb_mount;;
	unmount) prompt_usb_unmount;;
	eject)   prompt_usb_eject;;

esac
