#!/usr/bin/env sh

THING="$(usb_get_mounted)\n$(usb_get_unmounted)"

if [ -z "$THING" ]; then
	notify_usb "no drives available!"
    exit 1
fi



TARGET=$(echo "$THING" | dmenu -p "eject")

if [ -z "$TARGET" ]; then
    exit 1
fi




BLOCKNAME=$(echo "$TARGET" | awk '{print $1}')



usb_eject $BLOCKNAME && notify_usb "$TARGET was ejected!"
