#!/usr/bin/env sh

# set $(bspc query -T -m | jq '.rectangle[]')
set $(dattr xywh $(pfd))
G="${3}x$4+$1+$2"

# x=$1
# y=$2
# w=$3
# h=$4

import -window root -crop $G png:- | xclip -selection clipboard -t image/png
