#!/usr/bin/env sh

fname="${SAMPLER_SAVE_DIRECTORY:-$(pwd)}/$(date +'%d_%m_%Y_%H_%M_%S').wav"
touch "$SAMPLER_TMP_FILE"

input="$(pactl list short sources | rg '\.monitor' | head -n1 | awk '{ print $2 }')"

not_running() {
	echo "$fname" > "$SAMPLER_TMP_FILE"
	command="ffmpeg -f pulse -i '$input' -ac 2 $(cat $SAMPLER_TMP_FILE)"
	echo "$command"
	prompt_yesno "sample?" &&
		bash -c "exec -a SAMPLER $command &" && notify_sampler "sampling"
}

running() {
	pkill -f SAMPLER && notify_sampler "saved as $(basename $(cat $SAMPLER_TMP_FILE))"
}

running || not_running &
